spring:
  application:
    name: spring-session-redis
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
#      password: password  # Optional, remove if not needed

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG
