spring:
  application:
    name: spring-session-jdbc-postgres
  session:
    store-type: jdbc # Use JDBC for session management
    jdbc:
      initialize-schema: always # Ensures schema.sql runs on startup (use 'never' in production)
  test:
    database:
      replace: none # Prevents Spring Boot from replacing the datasource with an in-memory database during tests
  security:
    user:
      name: admin
      password: admin123
  datasource:
    url: jdbc:postgresql://localhost:5432/session_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always  # Ensures schema.sql runs on startup (use 'never' in production)
      platform: postgres # Prevents Hibernate from overriding the jsonb data type with varchar data type.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org:
      springframework:
        security: DEBUG
